# -*- coding: utf-8 -*-
"""AnáliseDaDengue2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mELUUfxy5RCqcuW1UMaGIqoeqmIknsYA
"""

# ==========================================
# ETAPA 1: INSTALAÇÃO DA DEPENDÊNCIA AUSENTE
# ==========================================

# ==========================================
# ETAPA 2: IMPORTAÇÃO, CONFIGURAÇÃO E CONEXÃO COM MONGODB
# ==========================================
import pandas as pd
import pymongo
from pymongo import MongoClient
from IPython.display import display
import matplotlib.pyplot as plt
import seaborn as sns
import io
import requests
import time
import re

MONGO_URI = "localhost:27017"
DB_NAME = "bigdata_dengue_rj"

def get_mongo_collection(collection_name):
    """Conecta ao MongoDB e retorna a coleção desejada."""
    try:
        client = MongoClient(MONGO_URI)
        db = client[DB_NAME]
        print(f"Conectado ao MongoDB: {DB_NAME}")
        return db[collection_name]
    except Exception as e:
        print(f"Erro ao conectar ao MongoDB: {e}")
        return None

# ==========================================
# ETAPA 3: CARGA INICIAL (DATALAKE) - DO GITHUB PARA O MONGODB
# ==========================================

def listar_arquivos_github(usuario, repositorio, pasta):
    """Usa a API do GitHub para listar arquivos em um diretório."""
    url_api = f"https://api.github.com/repos/{usuario}/{repositorio}/contents/{pasta}"
    try:
        response = requests.get(url_api)
        if response.status_code == 200:
            return response.json()
    except:
        pass
    print(f"      ❌ ERRO NA API (Pasta: {pasta})")
    return []

def inserir_em_lotes(colecao, dataframe, tamanho_lote=1000):
    """
    Insere dados em pedaços menores para evitar queda de conexão.
    """
    registros = dataframe.to_dict("records")
    total = len(registros)
    print(f"   ...Iniciando inserção de {total} registros no MongoDB...")

    for i in range(0, total, tamanho_lote):
        lote = registros[i : i + tamanho_lote]
        try:
            colecao.insert_many(lote)
            if i % 5000 == 0 and i > 0:
                print(f"      - Progresso: {i}/{total}...")
        except Exception as e:
            print(f"      ❌ Erro no lote {i}: {e}")
            time.sleep(2)
            try:
                colecao.insert_many(lote)
                print(f"      - Lote {i} recuperado e inserido.")
            except:
                print(f"      - Lote {i} perdido.")

def carregar_csvs_para_mongo():
    print("--- Iniciando Carga dos CSVs do GitHub para o MongoDB ---")

    GITHUB_USER = "RoPedro"
    GITHUB_REPO = "csv-dados-av1-denis"

    # ---------------------------------------------------------
    # PARTE 1: MEMÓRIA (DOWNLOAD E PROCESSAMENTO)
    # ---------------------------------------------------------

    col_dengue = get_mongo_collection("casos_dengue")
    col_chuva = get_mongo_collection("precipitacao_chuva")

    # 1. LIMPEZA PRÉVIA
    if col_dengue is not None: col_dengue.delete_many({})
    if col_chuva is not None: col_chuva.delete_many({})

    # ---------------------------------------------------------
    # PROCESSO 1: DADOS DE DENGUE
    # ---------------------------------------------------------
    print(f"\n1. Buscando dados de DENGUE na pasta (Memória)...")
    arquivos_dengue = listar_arquivos_github(GITHUB_USER, GITHUB_REPO, "dengue_data")
    lista_dengue = []

    for arq in arquivos_dengue:
        if arq['name'].lower().endswith('.csv'):
            print(f"   ⬇️ Baixando: {arq['name']}")
            try:
                # Tenta ler com vírgula (padrão GitHub)
                df = pd.read_csv(arq['download_url'], sep=',', encoding='utf-8')

                if df.shape[1] < 2:
                    df = pd.read_csv(arq['download_url'], sep=';', encoding='utf-8')

                df.columns = df.columns.str.strip().str.lower()

                # Extração Inteligente do Município (Do nome do arquivo)
                try:
                    # Remove prefixo RJ_ e sufixo de numeros
                    nome_limpo = arq['name'].replace("RJ_", "").split("_")[0]
                    # Regex para separar CamelCase (AngraDosReis -> Angra Dos Reis)
                    nome_formatado = re.sub(r'(?<!^)(?=[A-Z])', ' ', nome_limpo).upper()
                    df['municipio'] = nome_formatado
                except:
                    pass

                lista_dengue.append(df)
            except Exception as e:
                print(f"      ⚠️ Erro em {arq['name']}: {e}")

    if lista_dengue:
        df_dengue_final = pd.concat(lista_dengue, ignore_index=True)
        # Garante que colunas vazias virem None pro Mongo não reclamar
        df_dengue_final = df_dengue_final.where(pd.notnull(df_dengue_final), None)

        if col_dengue is not None:
            inserir_em_lotes(col_dengue, df_dengue_final)
            print("   ✅ DENGUE SALVO COM SUCESSO.")
        else:
            print("   ❌ Erro: Coleção 'casos_dengue' não encontrada.")

    # ---------------------------------------------------------
    #  PROCESSO 2: DADOS DE CHUVA
    # ---------------------------------------------------------
    print("\n2. Buscando dados de CHUVA na pasta 'pluv_data' (Memória)...")
    arquivos_chuva = listar_arquivos_github(GITHUB_USER, GITHUB_REPO, "pluv_data")
    if not arquivos_chuva: arquivos_chuva = listar_arquivos_github(GITHUB_USER, GITHUB_REPO, "Pluv_data")

    lista_chuva = []
    for arq in arquivos_chuva:
        if arq['name'].lower().endswith('.csv'):
            print(f"   ⬇️ Baixando: {arq['name']}")
            try:
                # Pula cabeçalho do INMET (8 linhas)
                df = pd.read_csv(arq['download_url'], sep=';', encoding='latin1', skiprows=8)

                # Validação extra de cabeçalho
                if 'Data' not in df.columns and 'DATA (YYYY-MM-DD)' not in df.columns:
                     df = pd.read_csv(arq['download_url'], sep=';', encoding='latin1', skiprows=9)

                # Renomear para padronizar
                df.rename(columns={'Data': 'data_medicao', 'DATA (YYYY-MM-DD)': 'data_medicao'}, inplace=True)

                # Extrai município do nome (INMET_..._MUNICIPÍO_...)
                partes = arq['name'].split('_')
                # Geralmente o município é a 5ª parte (índice 4)
                muni = partes[4] if len(partes) > 4 else "DESCONHECIDO"
                df['municipio'] = muni

                df.columns = df.columns.str.strip().str.lower()
                lista_chuva.append(df)
            except Exception as e:
                print(f"     ⚠️ Erro ao ler {arq['name']}: {e}")

    if lista_chuva:
        df_chuva_final = pd.concat(lista_chuva, ignore_index=True)
        # Remove coluna fantasma do pandas e converte NaNs
        df_chuva_final = df_chuva_final.loc[:, ~df_chuva_final.columns.str.contains('unnamed')]
        df_chuva_final = df_chuva_final.where(pd.notnull(df_chuva_final), None)

        if col_chuva is not None:
            inserir_em_lotes(col_chuva, df_chuva_final)
            print("   ✅ CHUVA SALVA COM SUCESSO.")

    print("\n--- FIM DA CARGA ---")

if __name__ == "__main__":
    carregar_csvs_para_mongo()

# ==========================================
# ETAPA 4: ETL FINAL
# ==========================================

# Variável global
df_final_global = None

def limpar_valor_numerico(valor):
    """Auxiliar: Transforma '12,5' (string) em 12.5 (float)"""
    if valor is None: return 0.0
    if isinstance(valor, (int, float)): return float(valor)
    try:
        return float(str(valor).replace(',', '.'))
    except:
        return 0.0

def encontrar_coluna_por_padrao(dataframe, padroes):
    for col_real in dataframe.columns:
        for padrao in padroes:
            if padrao.lower() in col_real.lower():
                return col_real
    return None

def executar_etl():
    global df_final_global

    pd.set_option('display.max_rows', None)
    pd.set_option('display.max_columns', None)

    print("--- 1. EXTRAÇÃO: Baixando dados do MongoDB Atlas... ---")

    col_dengue = get_mongo_collection("casos_dengue")
    col_chuva = get_mongo_collection("precipitacao_chuva")

    if col_dengue is None or col_chuva is None:
        print("   ❌ Erro de conexão.")
        return

    df_dengue = pd.DataFrame(list(col_dengue.find({}, {"_id": 0})))
    df_chuva = pd.DataFrame(list(col_chuva.find({}, {"_id": 0})))

    if df_dengue.empty or df_chuva.empty:
        print("   ❌ Erro: Tabelas vazias.")
        return None

    print(f"   -> Registros extraídos (Total Bruto): Dengue={len(df_dengue)} | Chuva={len(df_chuva)}")
    print("\n--- 2. TRANSFORMAÇÃO ---")

    # ====================================================
    # TRATAMENTO DA DENGUE
    # ====================================================
    col_data_dengue = encontrar_coluna_por_padrao(df_dengue, ['data_inise', 'dt_notific', 'data', 'dt_sin_pri'])
    if not col_data_dengue: col_data_dengue = df_dengue.columns[0]

    df_dengue['data_obj'] = pd.to_datetime(df_dengue[col_data_dengue], errors='coerce')
    df_dengue = df_dengue[df_dengue['data_obj'].dt.year == 2024].copy() # Filtro 2024

    df_dengue['casos'] = pd.to_numeric(df_dengue['casos'], errors='coerce').fillna(0)
    df_dengue['mes_ano'] = df_dengue['data_obj'].dt.to_period('M')
    df_dengue['municipio'] = df_dengue['municipio'].astype(str).str.upper().str.strip()

    # Agregação Dengue
    dengue_mensal = df_dengue.groupby(['municipio', 'mes_ano'])['casos'].sum().reset_index()
    dengue_mensal = dengue_mensal.sort_values(['mes_ano', 'municipio'])

    print("\n--- [PLANILHA 1] Dados de Dengue (Ordenado por Mês) ---")
    cols_dengue_view = ['mes_ano', 'municipio', 'casos']
    display(dengue_mensal[cols_dengue_view])

    # ====================================================
    # TRATAMENTO DA CHUVA
    # ====================================================
    col_chuva_valor = encontrar_coluna_por_padrao(df_chuva, ['precipita', 'total', 'chuva', 'mm'])
    if not col_chuva_valor: col_chuva_valor = df_chuva.columns[1]

    col_data_chuva = encontrar_coluna_por_padrao(df_chuva, ['data_medicao', 'data', 'dt_medicao'])
    if not col_data_chuva: col_data_chuva = 'data_medicao'

    df_chuva['chuva_tratada'] = df_chuva[col_chuva_valor].apply(limpar_valor_numerico)
    df_chuva['data_obj'] = pd.to_datetime(df_chuva[col_data_chuva], errors='coerce')
    df_chuva = df_chuva[df_chuva['data_obj'].dt.year == 2024].copy() # Filtro 2024

    df_chuva['mes_ano'] = df_chuva['data_obj'].dt.to_period('M')
    df_chuva['municipio'] = df_chuva['municipio'].astype(str).str.upper().str.strip()


    chuva_exibicao = df_chuva.groupby(['municipio', 'mes_ano'])['chuva_tratada'].sum().reset_index()
    chuva_exibicao.rename(columns={'chuva_tratada': 'precipitacao'}, inplace=True)
    chuva_exibicao = chuva_exibicao.sort_values(['mes_ano', 'municipio'])

    print("\n--- [PLANILHA 2] Dados de Chuva (Detalhado por Estação) ---")
    cols_chuva_view = ['mes_ano', 'municipio', 'precipitacao']
    display(chuva_exibicao[cols_chuva_view])

    # ====================================================
    # PREPARAÇÃO PARA INTEGRAÇÃO
    # ====================================================
    # Cria uma cópia para agrupar o Rio de Janeiro APENAS para o merge final
    df_chuva_agrupado = df_chuva.copy()

    filtro_rj = df_chuva_agrupado['municipio'].str.startswith('RIO DE JANEIRO')
    df_chuva_agrupado.loc[filtro_rj, 'municipio'] = 'RIO DE JANEIRO'

    # Re-agrega com o RJ unificado
    chuva_final_merge = df_chuva_agrupado.groupby(['municipio', 'mes_ano'])['chuva_tratada'].sum().reset_index()
    chuva_final_merge.rename(columns={'chuva_tratada': 'precipitacao'}, inplace=True)

    # ====================================================
    # INTEGRAÇÃO
    # ====================================================
    print("\n--- 3. INTEGRAÇÃO ---")
    # Usa o 'chuva_final_merge' que tem o RJ unificado
    df_final = pd.merge(dengue_mensal, chuva_final_merge, on=['municipio', 'mes_ano'], how='inner')

    df_final['mes_ref'] = df_final['mes_ano'].astype(str)
    df_final['mes_num'] = df_final['mes_ano'].dt.month

    # Ordenação final
    df_final = df_final.sort_values(['mes_ano', 'municipio'])
    df_final_global = df_final

    print("\n--- [PLANILHA 3] Dataset Final Consolidado (RJ Unificado) ---")
    cols_final_view = ['mes_ano', 'municipio', 'casos', 'precipitacao']
    display(df_final[cols_final_view])

    return df_final

if __name__ == "__main__":
    executar_etl()

# ==========================================
# ETAPA 5: ANÁLISE E RELATÓRIO GRÁFICO
# ==========================================

def gerar_relatorio_grafico():
    print("--- Iniciando Geração de Relatório Gráfico ---")

    # 1. VERIFICAÇÃO DE SEGURANÇA
    try:
        if df_final_global is None or len(df_final_global) == 0:
            print("❌ Erro: Nenhum dado disponível. Rode a Etapa 4 (ETL) primeiro.")
            return
    except NameError:
        print("❌ Erro: Variável 'df_final_global' não encontrada. Rode a Etapa 4 primeiro.")
        return

    # 2. PREPARAÇÃO DOS DADOS
    # Ordena por número do mês para garantir a ordem cronológica no eixo X
    df_sorted = df_final_global.sort_values(['mes_num', 'municipio'])

    # Configurações estéticas globais
    sns.set_style("whitegrid")
    plt.rcParams['figure.figsize'] = (20, 8)
    plt.rcParams['axes.titlesize'] = 18
    plt.rcParams['axes.labelsize'] = 14

    # ==============================================================================
    # GRÁFICO 1: Casos de Dengue Mensais por Município
    # ==============================================================================
    print("\nGerando Gráfico 1: Casos de Dengue por Município...")

    plt.figure(figsize=(22, 10))

    sns.barplot(
        data=df_sorted,
        x='mes_ref',
        y='casos',
        hue='municipio', # Separa as barras por cor
        palette='tab20'  # Paleta com muitas cores para distinguir os municípios
    )

    plt.title('Casos de Dengue Mensais por Município em 2024')
    plt.xlabel('Mês')
    plt.ylabel('Número de Casos')
    plt.xticks(rotation=45)
    plt.legend(title='Município', bbox_to_anchor=(1.01, 1), loc='upper left')
    plt.tight_layout()
    plt.show()

    # ==============================================================================
    # GRÁFICO 2: Precipitação Mensal por Município
    # ==============================================================================
    print("\nGerando Gráfico 2: Precipitação Mensal por Município...")

    plt.figure(figsize=(22, 10))

    sns.lineplot(
        data=df_sorted,
        x='mes_ref',
        y='precipitacao',
        hue='municipio',
        style='municipio', # Adiciona estilos de linha diferentes para ajudar na distinção
        markers=True,
        dashes=False,
        palette='tab20',
        linewidth=2,
        markersize=8
    )

    plt.title('Precipitação Mensal (mm) por Município em 2024')
    plt.xlabel('Mês')
    plt.ylabel('Precipitação Total (mm)')
    plt.xticks(rotation=45)
    plt.legend(title='Município', bbox_to_anchor=(1.01, 1), loc='upper left')
    plt.tight_layout()
    plt.show()

    # ==============================================================================
    # GRÁFICO 3: Correlação Detalhada - Dengue (Barras) vs Chuva (Linhas)
    # ==============================================================================
    print("\nGerando Gráfico 3: Correlação Detalhada por Município...")

    fig, ax1 = plt.subplots(figsize=(22, 10))

    # --- EIXO 1 (ESQUERDA): BARRAS DE DENGUE ---
    sns.barplot(
        data=df_sorted,
        x='mes_ref',
        y='casos',
        hue='municipio',
        palette='tab20',
        ax=ax1,
        alpha=0.6, # Transparência para ver as linhas passando por cima
        dodge=True # Barras lado a lado
    )

    ax1.set_xlabel('Mês')
    ax1.set_ylabel('Número de Casos de Dengue', color='black', fontweight='bold')
    ax1.tick_params(axis='y', labelcolor='black')
    ax1.set_xticklabels(ax1.get_xticklabels(), rotation=45)

    # Remove a legenda do barplot para não duplicar
    ax1.get_legend().remove()

    # --- EIXO 2 (DIREITA): LINHAS DE CHUVA ---
    ax2 = ax1.twinx()

    sns.lineplot(
        data=df_sorted,
        x='mes_ref',
        y='precipitacao',
        hue='municipio',
        style='municipio',
        markers=True,
        dashes=False,
        palette='tab20', # Mesma paleta para manter consistência das cores
        ax=ax2,
        linewidth=3,
        markersize=9,
        legend='full' # Mostra a legenda completa aqui
    )

    ax2.set_ylabel('Precipitação Total (mm)', color='darkblue', fontweight='bold')
    ax2.tick_params(axis='y', labelcolor='darkblue')

    plt.title('Casos de Dengue vs. Precipitação Mensal por Município (2024)', fontsize=16)

    # Ajuste da legenda para ficar fora do gráfico
    sns.move_legend(ax2, "upper left", bbox_to_anchor=(1.02, 1), title='Município')

    plt.tight_layout()
    plt.show()

    # ==============================================================================
    # ANÁLISE ESTATÍSTICA E CONCLUSÃO
    # ==============================================================================
    # Calcula a correlação global do estado para o resumo
    df_estado = df_sorted.groupby('mes_ref')[['casos', 'precipitacao']].sum().reset_index()
    correlacao = df_estado['casos'].corr(df_estado['precipitacao'])
    total_casos = df_estado['casos'].sum()
    mes_pico = df_estado.loc[df_estado['casos'].idxmax()]['mes_ref']

    print("\n📊 --- RESUMO ESTATÍSTICO (GLOBAL DO ESTADO) ---")
    print(f"-> Total de Casos Analisados (2024): {int(total_casos)}")
    print(f"-> Mês com Maior Incidência: {mes_pico}")
    print(f"-> Correlação de Pearson (Chuva vs Dengue): {correlacao:.4f}")

    print("\n📝 --- CONCLUSÃO AUTOMÁTICA ---")
    if correlacao > 0.6:
        print(">> O coeficiente indica uma FORTE correlação positiva.")
        print(">> Interpretação: O aumento das chuvas está fortemente ligado ao aumento de casos neste período.")
    elif correlacao > 0.3:
        print(">> O coeficiente indica uma correlação MODERADA.")
        print(">> Interpretação: Existe relação, mas outros fatores também influenciam.")
    elif correlacao < -0.3:
        print(">> O coeficiente indica uma correlação NEGATIVA.")
        print(">> Interpretação: O pico de chuva não coincidiu diretamente com o pico de casos.")
    else:
        print(">> O coeficiente indica uma correlação FRACA ou INEXISTENTE.")
        print(">> Interpretação: Neste recorte de dados, a chuva não parece ser o fator determinante principal.")

if __name__ == "__main__":
    gerar_relatorio_grafico()
